#!/usr/bin/perl -w -I../perllib
#
# server:
# XMLRPC server.
#
# To run it you need these lines in an Apache config:
#     Options +ExecCGI
#     SetHandler fastcgi-script
#
#
# Copyright (c) 2004 UK Citizens Online Democracy. All rights reserved.
# Email: chris@mysociety.org; WWW: http://www.mysociety.org/
#

my $rcsid = ''; $rcsid .= '$Id: server,v 1.3 2004-10-14 14:14:21 chris Exp $';

use FCGI;
use mySociety::DaDem;   # client interface
use mySociety::VotingArea;
use DaDem;
use XMLRPC::Transport::HTTP;

my $req = FCGI::Request();

while ($req->Accept() >= 0) {
    my $s = XMLRPC::Transport::HTTP::CGI->dispatch_to('DaDem')->handle();
}

