#!/usr/bin/perl -w
#
# server:
# XMLRPC server.
#
# To run it you need these lines in an Apache config:
#     Options +ExecCGI
#     SetHandler fastcgi-script
#
#
# Copyright (c) 2004 UK Citizens Online Democracy. All rights reserved.
# Email: chris@mysociety.org; WWW: http://www.mysociety.org/
#

my $rcsid = ''; $rcsid .= '$Id: server,v 1.2 2004-10-14 14:13:44 francis Exp $';

use FCGI;
use DaDem;
use XMLRPC::Transport::HTTP;

my $req = FCGI::Request();

while ($req->Accept() >= 0) {
    my $s = XMLRPC::Transport::HTTP::CGI->dispatch_to('DaDem')->handle();
}

