#!/usr/bin/perl -w -I../perllib
#
# server:
# XMLRPC server.
#
# Copyright (c) 2004 UK Citizens Online Democracy. All rights reserved.
# Email: chris@mysociety.org; WWW: http://www.mysociety.org/
#

my $rcsid = ''; $rcsid .= '$Id: server,v 1.2 2004-10-15 09:16:31 francis Exp $';

use FCGI;
use mySociety::MaPit;   # client interface
use mySociety::VotingArea;
use MaPit;
use XMLRPC::Transport::HTTP;

use mySociety::WatchUpdate;
my $W = new mySociety::WatchUpdate();

my $req = FCGI::Request();

while ($req->Accept() >= 0) {
    my $s = XMLRPC::Transport::HTTP::CGI->dispatch_to('MaPit')->handle();
    $W->exit_if_changed();
}




