#!/usr/bin/perl -w -I../perllib
#
# server:
# RABX server for MaPit.
#
# Copyright (c) 2004 UK Citizens Online Democracy. All rights reserved.
# Email: chris@mysociety.org; WWW: http://www.mysociety.org/
#

my $rcsid = ''; $rcsid .= '$Id: server,v 1.7 2004-11-10 12:29:57 chris Exp $';

use FCGI;
use mySociety::MaPit;   # client interface
use mySociety::VotingArea;
use MaPit;
use RABX;

use mySociety::WatchUpdate;
my $W = new mySociety::WatchUpdate();

my $req = FCGI::Request();

while ($req->Accept() >= 0) {
    RABX::Server::CGI::dispatch(
            'MaPit.get_voting_areas' => sub {
                return MaPit::get_voting_areas($_[0]);
            },
            'MaPit.get_voting_area_info' => sub {
                return MaPit::get_voting_area_info($_[0]);
            },
            'MaPit.get_voting_areas_info' => sub {
                return MaPit::get_voting_areas_info($_[0]);
            }
        );
    $W->exit_if_changed();
}




