#!/bin/bash

/home/francis/fiddle/flex/bin/mxmlc -output ../../web/UKTransitTime.swf -source-path+=/home/francis/devel/mysociety/iso/flash/uk/libs/modestmaps -title "CoL" -creator "Francis" -publisher "mySociety" ./src/UKTransitTime.as

