#!/bin/bash

/home/francis/fiddle/flex/bin/mxmlc -debug=true -output ../../web/UKTransitTime.swf -source-path+=/home/francis/devel/mysociety/iso/flash/uk/libs/modestmaps -title "CoL" -creator "Francis" -publisher "mySociety" ./src/ColUKTransitTime.as

